version: "3"

services:
  mariadb:
    container_name: "ccwesteinde_mariadb"
    image: wodby/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ccwesteindeRootPass
      MYSQL_DATABASE: ccwesteinde
      MYSQL_USER: ccwesteindeUser
      MYSQL_PASSWORD: ccwesteindePass
  php:
    container_name: "ccwesteinde_php"
    image: wodby/php:7.4
    depends_on:
      - mariadb
      - redis
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      MYSQL_DATABASE: ccwesteinde
      MYSQL_HOSTNAME: mariadb
      MYSQL_USER: ccwesteindeUser
      MYSQL_PASSWORD: ccwesteindePass
      REDIS_HOST: redis
    volumes:
      - ./:/var/www/html:cached
  nginx:
    container_name: "ccwesteinde_nginx"
    image: wodby/nginx:latest
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/
      NGINX_VHOST_PRESET: php
    volumes:
      - ./:/var/www/html:cached
  redis:
    container_name: "ccwesteinde_redis"
    image: wodby/redis:latest
  mailhog:
    container_name: "ccwesteinde_mailhog"
    image: mailhog/mailhog:latest
